version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - clipcb_app
      - easyocr_app

  clipcb_app:
    build: ./services/clipcb_app
    command: gunicorn --bind 0.0.0.0:5001 clipcb:app
    ports:
      - "5001:5001"
    networks:
      - my_network

  easyocr_app:
    build: ./services/easyocrcb_app
    command: gunicorn --bind 0.0.0.0:5002 easyocrcb:app
    ports:
      - "5002:5002"
    networks:
      - my_network
#
#  metamodel_app:
#    build: ./services/metamodel_app
#    command: gunicorn --bind 0.0.0.0:5003 metamodel:app
#    ports:
#      - "5003:5003"
#    networks:
#      - my_network

networks:
  my_network: